force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/LoanId__c.field-meta.xml
<CustomField>
    <fullName>LoanId__c</fullName>
    <label>LoanId</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Repayment_Period_Months__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Period_Months__c</fullName>
    <label>Repayment Period Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReferredLoanController.cls
public with sharing class ReferredLoanController {

    @AuraEnabled
    public static List<Loan__c> getLoans(){

        System.debug('Retrieving loans..');
        return [SELECT LoanId__c, Name, Amount__c, Repayment_Period_Months__c, Status__c
            FROM Loan__c
            WHERE Status__c= 'Referred'
            ORDER BY  LoanId__c DESC ];
    }

    @AuraEnabled
    public static Loan__c updateLoan(Loan__c loan){
        upsert loan;
        System.debug('upserting via reviewer');
        System.debug(loan);
        return loan;
    }

    @AuraEnabled
    public static Loan__c getCredit(Loan__c loan){
        loan.Credit_Score__c = Integer.valueof((Math.random() * 10));
        upsert loan;
        System.debug('Upserting after getting credit score');
        System.debug(loan);
        return loan;
    }
}