force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/LoanId__c.field-meta.xml
<CustomField>
    <fullName>LoanId__c</fullName>
    <label>LoanId</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Repayment_Period_Months__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Period_Months__c</fullName>
    <label>Repayment Period Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoanController.cls
public with sharing class LoanController {

    @AuraEnabled
    public static List<Loan__c> getLoans(){

        System.debug('Retrieving loans..');
        return [SELECT LoanId__c, Name, Amount__c, Repayment_Period_Months__c, Status__c
            FROM Loan__c
            WHERE OwnerId =: userInfo.getUserId()
            ORDER BY  LoanId__c DESC];
    }

    @AuraEnabled
    public static Loan__c saveLoan(Loan__c loan){
        if(loan.Amount__c > 5000 || loan.Amount__c < 1000) {
            loan.Status__c = 'Rejected';
        } else if (loan.Amount__c > 3000) {
            loan.Status__c = 'Referred';
        } else {
            loan.Status__c = 'Approved';
        }
        upsert loan;
        return loan;
    }
}